### ISSUE TITLE
Collision while merging flist

### ISSUE THREAD

**Issue by serboctor** [threefoldtech/0-flist#12]
Currently there is not defined behavior for collision handling which makes it hard to predict how the merge is going to behave and the final output of the flist.

**Comment by zaibon** [comment]
I don't think that' right.
There is a define behavior, the higher layer should have priority and overwrite lower layers. 
@maxux can you validate my words ?

And we should clearly explain this in the docs.

**Comment by serboctor** [comment]
@zaibon I opened this issue based on input from @maxux

**Comment by maxux** [comment]
Actually I told Sarah there is no defined behavior clearly used. What you
explain is the expected behavior but this was never tested, even jumpscale
version was not stable about this for some obscure reasons.

I asked to open an issue to keep track of this and clearly define this :)

**Comment by zaibon** [comment]
I see. But the code currently as it is written does one of the two. I don't see any way it could be unpredictable, or that would be a pretty strange bug.

So let's have a look at how it's done today and document.

**Comment by maxux** [comment]
From my tests, file priority follows order of the arguments provided.
In simple words: if file already exists when merging, it's ignored.
```
zflist [...] --merge flist1.flist --merge flist2.flist
```
Files found on flist1 have higher priority on files on flist2.

**Comment by maxux** [comment]
Documentation updated via 46be3471abb3289af0b6cbdcff9cad75b80ad473
Note can be found: https://github.com/threefoldtech/0-flist#merge-priority
