### ISSUE TITLE
Extend flist to support file uid/gid in addition with username/groupname

### ISSUE THREAD

**Issue by maxux** [threefoldtech/0-flist#28]
Current version of flist stores only username and groupname for files and directories permissions. This is based on a legacy (but good intention) decision to make a portable definition of group and user.

But on runtime, this lead to several issues, eg:
- When doing an image of a stored filesystem, we can't use host mapping
- When reading flist for container like `0-fs` does, process runs on host, does the mapping with host and is not inline with expected container.

Storing uid/gid from source and forwarding to the end is the only portable solution to not depend on something on runtime.

Current flist format should be extended to support `UID` and `GID` inside ACL.

This is linked with https://github.com/threefoldtech/0-fs/issues/31

**Comment by zaibon** [comment]
This is nice. I think I've seen some flist where they use special users and that were giving some issue because of it. So I like this very much :-P

Does it mean zflist will need to be updated too ?

**Comment by maxux** [comment]
Yep, new information have to be added when creating flist. But 0-fs and zflist will be retrocompatible :)
