### ISSUE TITLE
flist integration in zero-os

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/0-flist#6]
new method in zero-os to do some basic functions using the flist library

- packaging of dir to flist 
    - flist put in source container/vm on specific location
    - starts from specified dir
    - can change destination dir e.g. /opt/build to /
- packaging will do following
    - compression/encr
    - create flist
    - upload to redis compatible server of choice
- result is
    - populated redis server for MD
    - flist in sqlite format or also on other redis server (in hset location)

let kristof review specs

**Comment by zaibon** [comment]
@despiegk please review: https://github.com/threefoldtech/0-core/issues/20
